"""Offline corpus-level merge-only entity resolution over Native entities.

This package is intentionally independent from ``evaluation`` and executable
``scripts``.  Orchestration supplies a complete immutable extraction snapshot;
the pipeline emits a reproducible merge plan and a complete mention mapping.
"""

from .candidates import acronym, generate_candidate_pairs
from .canonicalization import CanonicalizationResult, canonicalize_clusters
from .clustering import BlockedMerge, ClusterResult, constrained_cluster
from .decisions import DecisionBatch, JudgeBudgetExceededError, decide_pairs
from .embeddings import (
    EMBEDDING_CACHE_SCHEMA_VERSION,
    EMBEDDING_PROFILE_TEXT_VERSION,
    AsyncOllamaEmbedClient,
    EmbeddingAugmentationError,
    EmbeddingCacheError,
    EmbeddingDimensionError,
    EmbeddingNeighborEvidence,
    OllamaEmbeddingIdentity,
    augment_mentions_with_ollama_embeddings,
    build_lsh_cosine_neighbor_evidence,
    build_lsh_cosine_neighbor_map,
    embedding_cache_key,
    embedding_cache_path,
    mention_embedding_profile_text,
    profile_text_sha256,
)
from .judge import (
    FixedJudge,
    JudgeCache,
    JudgeIdentity,
    JudgeRelationship,
    JudgeResult,
)
from .models import (
    DEFAULT_ER_VERSION,
    ERConfig,
    ERDecisionPolicy,
    ERLineage,
    SCHEMA_VERSION,
    CandidatePair,
    CannotLink,
    CanonicalEntity,
    Cluster,
    CorpusSnapshot,
    EntityMention,
    EntityProfile,
    IncompleteCorpusError,
    MentionResolution,
    PairDecision,
    PairScore,
    RelationMention,
    content_hash,
    stable_mention_id,
    stable_relation_id,
)
from .ollama_judge import OllamaERJudge, SyncOllamaClient
from .pipeline import (
    ER_ARTIFACTS,
    ArtifactConflictError,
    EntityResolutionPipeline,
    ERResult,
)
from .profiles import (
    build_entity_profiles,
    build_native_entity_embedding_records,
    build_native_entity_profiles,
    entity_type_family,
    lexical_view,
    native_entity_id,
    normalize_text,
)
from .scoring import (
    pair_signals,
    score_candidate_pairs,
    score_pair,
)

__all__ = [
    "DEFAULT_ER_VERSION",
    "ER_ARTIFACTS",
    "SCHEMA_VERSION",
    "ArtifactConflictError",
    "BlockedMerge",
    "CandidatePair",
    "CannotLink",
    "CanonicalEntity",
    "CanonicalizationResult",
    "Cluster",
    "ClusterResult",
    "CorpusSnapshot",
    "DecisionBatch",
    "ERConfig",
    "ERDecisionPolicy",
    "ERLineage",
    "ERResult",
    "EMBEDDING_CACHE_SCHEMA_VERSION",
    "EMBEDDING_PROFILE_TEXT_VERSION",
    "AsyncOllamaEmbedClient",
    "EmbeddingAugmentationError",
    "EmbeddingCacheError",
    "EmbeddingDimensionError",
    "EmbeddingNeighborEvidence",
    "EntityMention",
    "EntityProfile",
    "EntityResolutionPipeline",
    "FixedJudge",
    "IncompleteCorpusError",
    "JudgeCache",
    "JudgeBudgetExceededError",
    "JudgeIdentity",
    "JudgeRelationship",
    "JudgeResult",
    "MentionResolution",
    "OllamaEmbeddingIdentity",
    "OllamaERJudge",
    "PairDecision",
    "PairScore",
    "RelationMention",
    "SyncOllamaClient",
    "acronym",
    "augment_mentions_with_ollama_embeddings",
    "build_lsh_cosine_neighbor_evidence",
    "build_lsh_cosine_neighbor_map",
    "build_entity_profiles",
    "build_native_entity_embedding_records",
    "build_native_entity_profiles",
    "canonicalize_clusters",
    "constrained_cluster",
    "content_hash",
    "decide_pairs",
    "entity_type_family",
    "embedding_cache_key",
    "embedding_cache_path",
    "generate_candidate_pairs",
    "lexical_view",
    "mention_embedding_profile_text",
    "native_entity_id",
    "normalize_text",
    "pair_signals",
    "profile_text_sha256",
    "score_candidate_pairs",
    "score_pair",
    "stable_mention_id",
    "stable_relation_id",
]
